image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
 DOCKER_DRIVER: overlay2


stages:
  - build
  - clean


build:
  stage: build
  script:
    - ls
    - export APP_VERSION=$(cat version)
    - echo $APP_VERSION
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u "$DOCKER_REGISTRY_USER" "$DOCKER_REGISTRY_HOST" --password-stdin
    - docker build --build-arg APP_VERSION=$APP_VERSION -t $DOCKER_REGISTRY_HOST/ralmn/go-git-sync .
    - docker tag $DOCKER_REGISTRY_HOST/ralmn/go-git-sync $DOCKER_REGISTRY_HOST/ralmn/go-git-sync:$APP_VERSION
    - docker push $DOCKER_REGISTRY_HOST/ralmn/go-git-sync
    - docker push $DOCKER_REGISTRY_HOST/ralmn/go-git-sync:$APP_VERSION
    - docker rmi $DOCKER_REGISTRY_HOST/ralmn/go-git-sync
    - docker rmi $DOCKER_REGISTRY_HOST/ralmn/go-git-sync:$APP_VERSION
