image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
 DOCKER_DRIVER: overlay2

services:
- docker:dind

stages:
  - build
  - deploy


build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - ls
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" "$DOCKER_REGISTRY_HOST" --password-stdin
    - docker build -t $DOCKER_REGISTRY_HOST/ralmn/go-git-sync .
    - docker commit $DOCKER_REGISTRY_HOST/ralmn/go-git-sync $DOCKER_REGISTRY_HOST/ralmn/go-git-sync:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY_HOST/ralmn/go-git-sync
    - docker push $DOCKER_REGISTRY_HOST/ralmn/go-git-sync:$CI_PIPELINE_ID

